### ISSUE TITLE
Typescript: the type definitions throw an error 

### ISSUE THREAD

**Issue by bdekok** [Q42/floating-focus-a11y#24]
Hi Q42-ers, the neighbours here :) 

When implementing this package inside of a typescript nuxt project, we get the following type definition error: 

```
node_modules/@q42/floating-focus-a11y/index.d.ts(2,50):                                       
nuxt:typescript 17:48:11
2:50 An implementation cannot be declared in ambient contexts.
    1 | export default class FloatingFocus {
  > 2 | 	constructor(container: Element = document.body) {}
      | 	                                                ^
    3 | }
```
Shouldn't the definition be:

```
 export default declare class FloatingFocus {
    constructor(container: Element);
 }
```

**Comment by guidobouman** [comment]
Hey @bdekok,

Thanks for mention this!

**Comment by guidobouman** [comment]
@bdekok Just to check: all good now?

**Comment by bdekok** [comment]
Bit of a late response but all is good now, cheers. We’re using it for the familiar orange site (groepsspelen). Quite like it though.
