### ISSUE TITLE
Respect more accessibility preferences by default

### ISSUE THREAD

**Issue by guidobouman** [Q42/floating-focus-a11y#38]
This package was designed with a sane default setup, but it lets the accessibility style preferences to the implementing party. With #37 we now respect `prefers-reduced-motion`. There are more options. Which ones should we cater to by default?

See:
- https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
- https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-contrast
- https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-transparency

**Comment by CptMeatball** [comment]
Closing this issue, as we do not include a default color by default and the transparency media query has not been implemented across browsers.
